version: "3.8"
services:
  postgreservis:
    container_name: postgreservis
    hostname: postgreservis
    image: postgres:latest
    env_file:
      - hizliservis/docker.env
    ports:
      - "5433:5432"
    volumes:
      - "postgresql-data-servis:/var/lib/postgresql/data"
    networks:
      - main_servis
    command: -p 5433
  app:
    container_name: app_servis
    hostname: app_servis
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - hizliservis/docker.env
    volumes:
      - static-data-servis:/srv/public
      - .:/srv/app
    expose:
      - 8001
    depends_on:
      - postgreservis
    command: gunicorn hizliservis.wsgi:application --bind 0.0.0.0:8001
    networks:
      - main_servis
      - bridge_network

networks:
  main_servis:
  bridge_network:
    name: nginx_network
    driver: bridge

volumes:
  postgresql-data-servis:
  static-data-servis: